# Generated by Django 4.0.3 on 2023-03-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_and_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookListTest',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionListTest',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='DateCheckTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
    ]
