# Generated by Django 4.0.3 on 2023-03-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_and_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookListTest',
            fields=[
                ('lecture', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('book_type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchedQuestionListTest',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('page', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('theme', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='FaqAndEstimatedAnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('theme', models.IntegerField(null=True)),
                ('count', models.IntegerField(default=1)),
                ('keyword1', models.CharField(max_length=20, null=True)),
                ('keyword2', models.CharField(max_length=20, null=True)),
                ('keyword3', models.CharField(max_length=20, null=True)),
                ('answer', models.CharField(max_length=400, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedQuestionListTest',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=50)),
                ('page', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('theme', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='DateCheckTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='AnsweredQuestionListTest',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=50)),
                ('page', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('theme', models.IntegerField(null=True)),
                ('answer', models.CharField(max_length=400, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
    ]
