# Generated by Django 4.0.3 on 2023-03-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedAnswer',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('answer', models.CharField(max_length=400)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqList',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('keyword', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuestionListTest',
        ),
    ]
