# Generated by Django 4.0.3 on 2023-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datechecktest',
            name='day',
        ),
        migrations.RemoveField(
            model_name='datechecktest',
            name='month',
        ),
        migrations.RemoveField(
            model_name='datechecktest',
            name='year',
        ),
        migrations.AddField(
            model_name='datechecktest',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
