# Generated by Django 4.0.3 on 2023-02-01 00:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='buy_book',
        ),
        migrations.RemoveField(
            model_name='question',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student_name',
        ),
        migrations.AddField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.date.today)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.question')),
            ],
        ),
    ]
