# Generated by Django 4.0.3 on 2023-03-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0002_estimatedanswer_faqlist_delete_questionlisttest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstimatedAnswer',
            new_name='EstimatedAnswerTest',
        ),
        migrations.RenameModel(
            old_name='FaqList',
            new_name='FaqListTest',
        ),
    ]
