# Generated by Django 4.0.3 on 2023-03-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0003_rename_estimatedanswer_estimatedanswertest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestionListTest',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedQuestionListTest',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='FaqAndEstimatedAnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('keyword', models.CharField(max_length=200)),
                ('answer', models.CharField(blank=True, max_length=400)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.CreateModel(
            name='SearchedQuestionListTest',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name_and_id', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('number', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklisttest')),
            ],
        ),
        migrations.RemoveField(
            model_name='faqlisttest',
            name='book',
        ),
        migrations.DeleteModel(
            name='EstimatedAnswerTest',
        ),
        migrations.DeleteModel(
            name='FaqListTest',
        ),
    ]
