# Generated by Django 4.0.3 on 2023-04-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0003_alter_answeredquestionlisttest_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedquestionlisttest',
            name='date',
            field=models.DateField(default='2023-04-06'),
            preserve_default=False,
        ),
    ]
