# Generated by Django 4.0.3 on 2023-03-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0004_answeredquestionlisttest_extractedquestionlisttest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedquestionlisttest',
            name='student_name_and_id',
        ),
        migrations.AddField(
            model_name='answeredquestionlisttest',
            name='answer',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='answeredquestionlisttest',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extractedquestionlisttest',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faqandestimatedanswertest',
            name='answer',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='searchedquestionlisttest',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
