# Generated by Django 4.0.3 on 2023-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0005_remove_searchedquestionlisttest_student_name_and_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestionlisttest',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answeredquestionlisttest',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answeredquestionlisttest',
            name='theme',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extractedquestionlisttest',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extractedquestionlisttest',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extractedquestionlisttest',
            name='theme',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faqandestimatedanswertest',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faqandestimatedanswertest',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faqandestimatedanswertest',
            name='theme',
            field=models.IntegerField(null=True),
        ),
    ]
