# Generated by Django 4.0.3 on 2023-04-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0005_answeredquestionlisttest_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedquestionlisttest',
            name='date',
        ),
    ]
