# Generated by Django 4.0.3 on 2023-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0006_alter_answeredquestionlisttest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisttest',
            name='lecture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
