# Generated by Django 4.0.3 on 2023-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0007_extractedquestionlisttest_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedquestionlisttest',
            name='answer',
            field=models.TextField(default='Init'),
            preserve_default=False,
        ),
    ]
