# Generated by Django 4.0.3 on 2023-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0009_blacklist_booklist_searchedquestionlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedquestionlisttest',
            name='questionid',
            field=models.IntegerField(default='1234'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractedquestionlisttest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
