# Generated by Django 4.0.3 on 2023-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0010_extractedquestionlisttest_questionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedquestionlisttest',
            name='questionid',
        ),
        migrations.AddField(
            model_name='extractedquestionlisttest',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractedquestionlisttest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
