# Generated by Django 4.0.3 on 2023-04-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0011_remove_extractedquestionlisttest_questionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredquestionlisttest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='extractedquestionlisttest',
            name='student',
        ),
    ]
