# Generated by Django 4.0.3 on 2023-04-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0012_remove_answeredquestionlisttest_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestionlisttest',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
