# Generated by Django 4.0.3 on 2023-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0013_answeredquestionlisttest_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqandestimatedanswer',
            name='keyword1',
        ),
        migrations.RemoveField(
            model_name='faqandestimatedanswer',
            name='keyword2',
        ),
        migrations.RemoveField(
            model_name='faqandestimatedanswer',
            name='keyword3',
        ),
        migrations.AddField(
            model_name='faqandestimatedanswer',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
