# Generated by Django 4.0.3 on 2023-05-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0014_remove_faqandestimatedanswer_keyword1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtractedQuestionList',
            new_name='ExtractedAndAnsweredQuestionList',
        ),
        migrations.DeleteModel(
            name='AnsweredQuestionList',
        ),
    ]
