# Generated by Django 4.0.3 on 2023-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0015_rename_extractedquestionlist_extractedandansweredquestionlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedandansweredquestionlist',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
