# Generated by Django 4.0.3 on 2023-06-20 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_automate', '0016_extractedandansweredquestionlist_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractforview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('student', models.CharField(max_length=50)),
                ('page', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('theme', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_automate.booklist')),
            ],
        ),
    ]
